###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    webserver:
      image: nginx:alpine
      depends_on:
        - php-fpm
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "22222:80"

    node:
      image: "node:8"
      depends_on:
        - webserver
      user: "node"
      working_dir: /application
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/application
      expose:
        - "8081"
      command: "npm start"

    mailhog:
      image: mailhog/mailhog:latest
      depends_on:
        - webserver
      ports:
        - "22223:8025"

    mariadb:
      image: mariadb:10.1
      depends_on:
        - webserver
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=simplon
        - MYSQL_PASSWORD=simplon
      ports:
        - "22225:3306"

    postgres:
      image: postgres:9.6-alpine
      depends_on:
        - webserver
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=simplon
        - POSTGRES_PASSWORD=simplon
        - POSTGRES_DB=app
